name: Checkout
on: [push]

jobs:
    checkout-action:
        runs-on: ubuntu-latest
        steps:
            - name: List Files Before
              run: ls -a
            # https://github.com/marketplace/actions/checkout
            - uses: actions/checkout@v3
            - name: List Files After
              run: ls -a


    checkout:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              run: |
                git init
                git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
                git fetch origin
                git checkout main
            - name: List Files After Checkout
              run: |
                echo "Files after checkout:"
                ls -a