name: working-dir-and-shells
on: [push]
defaults:
    run:
        shell: bash
        # working-directory: ./de/ed
jobs:
    display-wd-info-ubuntu:
        runs-on: ubuntu-latest
        steps:
            - name: Display info ubuntu
              run: |
                pwd
                ls -a
                echo $GITHUB_SHA
                echo $GITHUB_REPOSITORY
                echo $GITHUB_WORKSPACE
            - name: Change working directory
              working-directory: /home/runner
              run: pwd
    display-wd-info-windows:
        runs-on: windows-latest
        defaults:
            run:
                shell: pwsh
        steps:
            - name: Display info windows
              run: |
                Get-Location
                dir
                Write-Output $env:GITHUB_SHA
                Write-Output $env:GITHUB_REPOSITORY
                Write-Output $env:GITHUB_WORKSPACE
            - name: Python shell
              shell: python
              run: |
                import platform
                print(platform.processor())